spring.application.name=yomu-liga

server.port=8084

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=liga_mod
spring.jpa.show-sql=true

spring.jackson.serialization.indent_output=true

achievement.service.base-url=https://loyal-wilona-b-m-rafi-ghalib-fideligo-2406495703-14f0a971.koyeb.app
achievement.service.daily-mission-path=/api/internal/league/achievements/clans/{clanId}/daily-mission-completion-percentage
